INSERT INTO `CUSTOMER_CATEGORY`(`CUSTOMER_CATEGORY_ID`,`CUSTOMER_CATEGORY_NAME`) VALUES (1,'BUSINESS');
INSERT INTO `CUSTOMER_CATEGORY`(`CUSTOMER_CATEGORY_ID`,`CUSTOMER_CATEGORY_NAME`) VALUES (2,'CONSUMER');

INSERT INTO `CUSTOMER_TYPE`(`CUSTOMER_TYPE_ID`,`CUSTOMER_TYPE_NAME`) VALUES (1,'STANDARD');
INSERT INTO `CUSTOMER_TYPE`(`CUSTOMER_TYPE_ID`,`CUSTOMER_TYPE_NAME`) VALUES (2,'PREMIUM');

